#!/bin/bash

seen=0
if [[ -d ".git" ]]; then
    (( seen++ ))
    git status
fi

# Loop through all child dirs
for dir in */; do
    if [[ -d "$dir/.git" ]]; then
        (( seen++ ))

        echo
        printf -- "%.s-" {1..25}
        echo
        echo "${dir%/}"
        printf -- "%.s-" {1..25}
        echo

        cd "$dir"
        git status
        cd ..
    fi
done

if [[ $seen == 0 ]]; then
    echo Directory does not contain any git repositories.
fi
