#!/bin/bash

# Check if dir is empty
validate_empty "."
VALIDATION_STATUS=$?

if [ "$VALIDATION_STATUS" -ne 0 ]; then
    echo "❌ ERROR: The previous command failed (Exit Code: $VALIDATION_STATUS)."
    exit 1
fi

npm init -y
touch index.js
git-init
